#
###################################
# Site wide configuration
####################################
#
title: Allen Lee's blog
email: al@allenlee.net
description: Allen Lee's blog about having cancer in the 21st century
url: http://allenlee.net

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  pygments
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Allen 李
  avatar: avatar.jpg
  job: "Software Engineer"
  bio: "I'm a programmer and a stage 4 cancer patient."
  email: al@allenlee.net
  rss: /atom.xml
  disqus-shortname: allenleenet
  twitter: allen_lee_
  facebook: allen.lee.812
  google:
    plus: #username
    analytics: UA-56089889-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
